# Generated by Django 5.1.2 on 2024-10-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('followed', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
